apiVersion: v1
kind: Pod
metadata:
  name: shared-volumes-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - "sleep 3600"
    volumeMounts:
    - name: test-vol
      mountPath: /scratch
  - name: otherbox
    image: busybox
    command:
    - sh
    - -c
    - "sleep 3600"
    volumeMounts:
    - name: test-vol
      mountPath: /other
  volumes:
  - name: test-vol
    emptyDir: {}
