apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - "sleep 3600"
    env:
    - name: MY_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: config
          key: MY_ENV_VAR
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: config-volume
    configMap:
      name: config
      items:
      - key: application.properties
        path: application.properties
