apiVersion: v1
kind: Pod
metadata:
  name: writer
spec:
  containers:
  - image: busybox
    name: busybox
    securityContext:
      readOnlyRootFilesystem: true
    command:
    - sh
    - -c
    - "touch /tmp/healthy && sleep 3600"
