apiVersion: v1
kind: LimitRange
metadata:
  name: low-resource-range
spec:
  limits:
  - max:
      memory: 500Mi
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-constraints
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-constraints
  template:
    metadata:
      labels:
        app: memory-constraints
    spec:
      containers:
      - name: memory-constrained
        image: nginx
        resources:
          limits:
            memory: "800Mi"

